version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: xckxx_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: data
      MYSQL_CHARSET: utf8
      MYSQL_COLLATION: utf8_general_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --character-set-server=utf8 --collation-server=utf8_general_ci

volumes:
  mysql_data:
